### ISSUE TITLE
Key error in TestLoadAnalysis.py

### ISSUE THREAD

**Issue by ashwinip5** [prithvisekhar/VehicalDiagnosticAlgo#2]
plt.plot(EngineLoadLess['Index'],EngineLoadLess['**engine_load**'],'g.')                           (Line-26,27)
Key Error : " engine_load " ---> " EngineLoad "

plt.plot(VehicleSpeedLess['Index'],VehicleSpeedLess['**Vehicle_speed**'],'g.')                  (Line-40,41)
Key Error : " Vehicle_speed " ---> " VehicleSpeed "

plt.plot(EngineRPMLess['Index'],EngineRPMLess['**engine_rpm**'],'g.')                            (Line-52,53)
Key Error : " engine_rpm " ---> " EngineRPM "

**Comment by rohitkumar0427** [comment]
Fixed
